#!/bin/sh

set -e

if [ "$1" = "configure" ]; then
        # Add an alternative for estudio
        update-alternatives \
	    --install \
		/usr/bin/estudio estudio /usr/bin/estudio-18.01 18011 \
            --slave \
		/usr/bin/vision2_demo vision2_demo \
					/usr/bin/vision2_demo-18.01 \
            --slave \
		/usr/bin/finish_freezing finish_freezing \
					/usr/bin/finish_freezing-18.01 \
            --slave \
		/usr/bin/esbuilder esbuilder \
					/usr/bin/esbuilder-18.01 \
            --slave \
		/usr/bin/ecb ecb /usr/bin/ecb-18.01 \
            --slave \
		/usr/bin/ec ec /usr/bin/ec-18.01 \
			--slave \
		/usr/bin/iron iron /usr/bin/iron-18.01
fi
